version: '3.8'

services:
  pdf-compressor:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/tmp/uploads
      - ./compressed:/tmp/compressed
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 